version: '3.1'

services:
  botadmin-db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: 'botadmin'
      POSTGRES_PASSWORD: 'botadmin'
      POSTGRES_DB: 'botadmin'
      POSTGRES_ROOT_PASSWORD: 'root'
    ports:
      - '5432:5432'
    expose:
      - '5432'