DROP TABLE IF EXISTS acc_tg_user;
create table acc_tg_user
(
    id          int8 generated by default as identity,
    balance     numeric(19, 2),
    data_create timestamp,
    email       varchar(255),
    first_name  varchar(255),
    last_name   varchar(255),
    phone       varchar(255),
    status      varchar(255),
    primary key (id)
)